31_API_delete_kategori
aldhisttd/2023_5pagib_cafe_be pull request #11
Opened 2023-12-24 22:17 UTC by FanyFadhilah

![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129471406/a8f6e071-e05d-4552-83fb-821216034365)

2023-12-26 21:26 UTC, FanyFadhilah commented
<img width="960" alt="fany" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129471406/d7a4dc7b-524f-446f-b393-d05361f3d94f">
<img width="960" alt="fany 1" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129471406/2402365f-95f3-4e71-aa04-5147ac636e6b">
<img width="960" alt="fany 2" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129471406/2cbfc2ed-0f33-432f-b9bc-abde75267410">
<img width="960" alt="fany 3" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129471406/000a5bf1-1549-4cc9-b1e8-45314278b129">
<img width="672" alt="fany 4" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129471406/d31e2664-bfb6-4f9c-ac0f-d6069be553f6">

ini revisinya pak @aldhi88

2023-12-27 05:09 UTC, aldhi88 requested changes
@FanyFadhilah 
- gak ada test postman nya
- kenapa ada file yg kamu hapus

2023-12-28 01:33 UTC, aldhi88 requested changes
@FanyFadhilah 

![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/16351933/2e7b2f61-adde-463c-b952-b240ae6dc385)

- dari hasil test postman kamu nunjukin bahwa kamu gak paham konsep, pelajari
- code kamu response nya knp di tambah2 sesuatu yg tidak sesuai api spec

2023-12-31 05:51 UTC, aldhi88 requested changes

2023-12-31 05:51 UTC, aldhi88 commented on kategori_delete.php
> +if (isset($_POST['kode'])) {
@FanyFadhilah gak usah ada validasi ini klo kamu gak buat else nya

2024-01-04 20:11 UTC, closed without merging