revisi 34_API_DATA_MENU
aldhisttd/2023_5pagib_cafe_be pull request #15
Opened 2023-12-26 13:09 UTC by Suhendri12Ok

<img width="960" alt="01" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470519/a6351f1a-287c-4265-af06-94ec8fe80fab">
<img width="960" alt="02" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470519/8126c007-32c2-4030-9c71-4d5a235b0cd4">
<img width="960" alt="03" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470519/4d9eccac-1f17-41d4-9fb6-00036006ef09">
<img width="604" alt="04" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470519/d20221d5-a2cd-4937-a016-62cef10e7ac4">
<img width="779" alt="05" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470519/61775b25-6a07-408a-9650-2890b6239673">
<img width="801" alt="06" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470519/71411049-9d03-434b-b97b-49e08ae92e1d">

@aldhi88

2023-12-27 05:06 UTC, aldhi88 requested changes

2023-12-27 05:06 UTC, aldhi88 commented on env.php.example
@Suhendri12Ok kenapa di hapus file ini

2023-12-27 05:06 UTC, aldhi88 commented on obat_read.php
> +    while ($row = mysqli_fetch_assoc($q)) {
@Suhendri12Ok harusnya gak perlu looping, dari hasil query kamu bisa konversi ke array tanpa loop, silahkan pelajari

2023-12-27 22:37 UTC, Suhendri12Ok commented
revisi
<img width="672" alt="suhen1" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470519/d63832ee-6e54-4fb7-93cd-12ac3e5e038c">
<img width="865" alt="suhen" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470519/86ee5635-4085-4794-af0c-1757facb28af">

2023-12-28 01:46 UTC, aldhi88 requested changes
@Suhendri12Ok ini response nya gak sesuai api spec, perhatikan lagi

2023-12-28 01:46 UTC, aldhi88 commented on obat_read.php
> +$koneksi = mysqli_connect('localhost', 'root', '', 'cafe');
@Suhendri12Ok ini untuk apa ! perhatikan code nya

2024-01-03 16:55 UTC, closed without merging