revisi 37_API_Update_Menu
aldhisttd/2023_5pagib_cafe_be pull request #17
Opened 2023-12-26 20:49 UTC by sitijamila32

![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/135223366/999c0821-f919-4a80-866e-1b83e697fa8f)
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/135223366/913e49bb-5a7f-4ae5-bc34-c2c6f6bb1002)

@aldhi88

2023-12-27 05:10 UTC, aldhi88 requested changes
@sitijamila32 , test postman kamu gak sesuai case di api spec

2023-12-27 22:25 UTC, sitijamila32 commented
revisi 
<img width="802" alt="ila" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/135223366/a60aa789-ba1c-4cbd-9465-5f2b22e0b1b2">
<img width="775" alt="ila1" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/135223366/ebaa84a4-4b5c-4922-ae23-6461c9efb99f">
<img width="866" alt="ila2" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/135223366/f6923070-dfe7-4fb9-a48c-703f39358c96">
<img width="733" alt="ila3" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/135223366/bb8776ab-1107-416c-9460-4ec118fdc20e">
<img width="867" alt="ila4" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/135223366/932f353a-c643-443e-a695-922324fff077">
<img width="673" alt="ila5" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/135223366/bcae9d52-8dfa-460d-b775-44d324e70cb3">

2023-12-28 01:53 UTC, aldhi88 requested changes

2023-12-28 01:53 UTC, aldhi88 commented on obat_update.php
> +$koneksi = mysqli_connect('localhost', 'root', '', 'cafe');
@sitijamila32 ini untuk apa lagi sih?

2023-12-28 01:53 UTC, aldhi88 commented on obat_update.php
> +            unlink('uploads/' . $gambar);
@sitijamila32 `upload/` gak usah lagi, nama gambar sudah ada upload/ nya

2023-12-28 01:53 UTC, aldhi88 commented on obat_update.php
> +        $namagambar = md5(time()) . $ext;
tambahkan `upload/` nya

2023-12-31 05:47 UTC, aldhi88 requested changes

2023-12-31 05:47 UTC, aldhi88 commented on obat_update.php
> +if (isset($_POST['kode'], $_POST['nama'], $_POST['kode_kategori'], $_POST['harga'])) {
@sitijamila32 trus klo ada yg tidak ada di dalam post apa response nya?, kamu buat validasi tapi gak tuntas,

2023-12-31 05:47 UTC, aldhi88 commented on obat_update.php
> +        unlink('upload/'.$gambar);
@sitijamila32 lah kok yg ini ? saya comment nya kan bukan yg ini yg di tambah upload/

2024-01-03 18:57 UTC, closed without merging