30_API_data_by_id
aldhisttd/2023_5pagib_cafe_be pull request #22
Opened 2023-12-28 00:11 UTC by Denihendriawan123

<img width="957" alt="deni1" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/133296433/2113f118-2ed3-4a57-88dc-59928faf70e0">
<img width="676" alt="deni2" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/133296433/d46258b0-c26d-4104-b409-475ca24b8206">
<img width="804" alt="deni3" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/133296433/5152d70b-a1a7-4dd5-b76e-38a844e5d074">

@aldhi88

2023-12-30 10:15 UTC, Denihendriawan123 commented
<img width="802" alt="deny" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/133296433/34a0e20c-6823-402a-adab-1f5bb78952fb">
<img width="800" alt="deny1" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/133296433/3dfeab87-7319-4722-ab8d-ef543e3f8f6b">
<img width="671" alt="deny2" src="https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/133296433/9c5a6f5d-4697-4cfe-8ff1-60a2f3dd48c3">

@aldhi88 izin pak revisi nya

2024-01-05 04:44 UTC, aldhi88 requested changes

2024-01-05 04:44 UTC, aldhi88 commented on kategori_read_one.php
> +if (isset($_GET['kode'])) {
@Denihendriawan123 gak usah ada validasi ini

2024-01-05 04:44 UTC, aldhi88 commented on kategori_read_one.php
> +    if ($query) {
@Denihendriawan123 ini harus ada else nya, respon error

2024-01-05 04:44 UTC, aldhi88 commented on kategori_read_one.php
> +        if ($kategoriData) {
@Denihendriawan123 disini gak perlu if else lagi, respon success aja disini

2024-01-08 04:24 UTC, aldhi88 approved these changes

2024-01-08 04:24 UTC, merged