36. API data delete menu
aldhisttd/2023_5pagib_cafe_be pull request #3
Opened 2023-12-22 16:52 UTC by rizkiiadriian

![ss 1](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/4bdd14e6-7690-4ffe-b93c-6dfbfb255190)

2023-12-24 14:05 UTC, rizkiiadriian commented
tolong dicek pak @aldhi88 
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/66f9fc07-f3e6-4a3b-965d-23943ecca42f)

2023-12-27 05:19 UTC, aldhi88 requested changes
@rizkiiadriian gak sesuai API spec

2023-12-30 09:53 UTC, rizkiiadriian commented on menu_delete.php
@aldhi88

2023-12-31 05:39 UTC, aldhi88 requested changes
@rizkiiadriian , harusnya ada proses menghapus file gambar nya juga

2024-01-07 10:25 UTC, closed without merging