36. api delete menu be
aldhisttd/2023_5pagib_cafe_be pull request #34
Opened 2024-01-08 12:49 UTC by rizkiiadriian

![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/8ac29180-6115-41d3-b3c4-293c2d35a804)
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/17ac7170-f232-4a1b-982c-d29f8181e0bd)
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/9d4a2ed2-c1e1-485f-812d-b08136aa68fe)

2024-01-08 15:54 UTC, aldhi88 requested changes

2024-01-08 15:54 UTC, aldhi88 commented on menu_delete.php
> +unlink($gambar);
@rizkiiadriian masukkan ke dalam kondisi klw delete data di DB berhasil

2024-01-09 01:47 UTC, rizkiiadriian commented on menu_delete.php
> +    unlink($gambar);
@aldhi88 saya pindah unlinknya aja supaya dapat nama gambar sebelum dihapus

2024-01-14 10:18 UTC, rizkiiadriian commented
@aldhi88 
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/ae04995b-a8d3-48f8-a739-83a388795bc4)
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/25bd91f8-06d0-40ed-b6ce-0299b451d035)
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/d104389b-3a31-4a02-9097-5cd0b48596bf)

2024-01-15 04:00 UTC, merged