38. API data api by kategori id
aldhisttd/2023_5pagib_cafe_be pull request #4
Opened 2023-12-22 17:00 UTC by rizkiiadriian

![ss 2](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/fe7db637-acbe-4bbf-b543-490198487c9e)

2023-12-24 13:56 UTC, rizkiiadriian commented
tolong dicek lg pak @aldhi88 
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/824355e7-ccd7-4cf6-8487-142f0149570f)
![image](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/c6987868-96df-438f-80f4-9fd5b85236ae)

2023-12-27 05:23 UTC, aldhi88 requested changes

2023-12-27 05:23 UTC, aldhi88 commented on kategori_read_one.php
@rizkiiadriian , perhatikan lagi, klo seperti itu, maka response nya akan selalu 200

2023-12-30 10:12 UTC, rizkiiadriian commented on kategori_read_one.php
@aldhi88 kalau ada yg salah kasi instruksi yg jelas pak

2024-01-08 06:30 UTC, rizkiiadriian commented
![Screenshot (22)](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/9d981f89-8184-44bf-a0cf-15a9bb754153)
![Screenshot (23)](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/184d4f7d-0d2b-49b4-97f4-74072a009b90)
![Screenshot (24)](https://github.com/aldhisttd/2023_5pagib_cafe_be/assets/129470362/732b4ecc-f2a3-4aff-8a4c-a3c9b1c5b77e)
ini revisiannya pak @aldhi88

2024-01-08 12:51 UTC, closed without merging